import React, { useState } from 'react';
import { X, Copy, Download, Check, FileText, Share2 } from 'lucide-react';
import { CityPulseReport } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: CityPulseReport | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, report }) => {
  const [copiedType, setCopiedType] = useState<string | null>(null);

  if (!isOpen || !report) return null;

  const generateMarkdown = () => {
    return `# 🏙️ ChaosGrid AI — Urban Navigation & Intelligence Brief
**Zone:** ${report.city}
**Timestamp:** ${report.timestamp || 'Real-time'}
**Safety Score:** ${report.safetyScore}/100 (${report.safetyLevel})

---
### 📌 Executive Summary
${report.summary}

---
### 🚨 Active Smart Alerts
${report.smartAlerts.map(a => `- [${a.type.toUpperCase()} - ${a.severity}] ${a.message}`).join('\n')}

---
### 🧭 Tactical Safe Routes
${report.safeRoutes.map(r => `1. ${r}`).join('\n')}

---
### 🍲 Cultural & Food Highlights
${report.culturalAndFoodSpots.map(s => `- **${s.name}** (${s.type}) | Budget: ${s.budget} | Vibe: ${s.vibe}\n  _${s.description || ''}_`).join('\n')}

---
### ⚖️ Route Comparison Matrix
**Recommended:**
${report.comparisonMatrix.recommended.map(r => `- **${r.name}** (Rating: ${r.score}): ${r.reason}`).join('\n')}

**Caution & Avoid:**
${report.comparisonMatrix.avoidOrCaution.map(a => `- ⚠️ **${a.name}** [Risk: ${a.risk}]: ${a.reason}`).join('\n')}

${report.transitSteps?.length ? `
---
### 🚶 Navigation Itinerary Checklist
${report.transitSteps.map(t => `- [ ] Step ${t.step} (${t.mode} - ${t.eta}): ${t.title} — ${t.instruction}`).join('\n')}
` : ''}

Generated by ChaosGrid AI for PromptWars Hackathon.
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopiedType('markdown');
    setTimeout(() => setCopiedType(null), 2000);
  };

  const handleCopySummary = () => {
    const text = `🚨 ChaosGrid AI Urban Brief: ${report.city}\nSafety Score: ${report.safetyScore}/100 (${report.safetyLevel})\n\n${report.summary}\n\nTop Safe Corridors:\n${report.safeRoutes.slice(0, 2).map(r => `• ${r}`).join('\n')}\n\nKey Alerts:\n${report.smartAlerts.slice(0, 2).map(a => `• [${a.type}] ${a.message}`).join('\n')}`;
    navigator.clipboard.writeText(text);
    setCopiedType('summary');
    setTimeout(() => setCopiedType(null), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `chaosgrid-${report.city.toLowerCase().replace(/[^a-z0-9]/g, '-')}-brief.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div role="dialog" aria-modal="true" aria-labelledby="export-modal-title" className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md animate-fade-in">
      <div className="relative w-full max-w-2xl rounded-2xl glass-panel p-6 shadow-2xl border border-cyan-500/20 text-slate-100 max-h-[90vh] flex flex-col">
        <button
          onClick={onClose}
          aria-label="Close export dialog"
          className="absolute top-4 right-4 p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition focus:outline-none focus:ring-2 focus:ring-cyan-400"
        >
          <X className="w-5 h-5" aria-hidden="true" />
        </button>

        <div className="flex items-center gap-3 mb-4">
          <div className="p-2.5 rounded-xl bg-purple-500/10 border border-purple-500/30 text-purple-400">
            <Share2 className="w-6 h-6" aria-hidden="true" />
          </div>
          <div>
            <h3 id="export-modal-title" className="text-lg font-bold text-white tracking-wide">Export & Share Urban Brief</h3>
            <p className="text-xs text-slate-400">Distribute safety protocols and navigation intelligence</p>
          </div>
        </div>

        {/* Action quick buttons */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4" role="group" aria-label="Export format options">
          <button
            onClick={handleCopyMarkdown}
            aria-label="Copy complete urban report as Markdown"
            className="flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700 text-xs font-semibold text-cyan-300 transition focus:outline-none focus:ring-2 focus:ring-cyan-400"
          >
            {copiedType === 'markdown' ? <Check className="w-4 h-4 text-emerald-400" aria-hidden="true" /> : <Copy className="w-4 h-4" aria-hidden="true" />}
            {copiedType === 'markdown' ? 'Copied Markdown!' : 'Copy Markdown'}
          </button>

          <button
            onClick={handleCopySummary}
            aria-label="Copy brief text summary for chat sharing"
            className="flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700 text-xs font-semibold text-emerald-300 transition focus:outline-none focus:ring-2 focus:ring-emerald-400"
          >
            {copiedType === 'summary' ? <Check className="w-4 h-4 text-emerald-400" aria-hidden="true" /> : <FileText className="w-4 h-4" aria-hidden="true" />}
            {copiedType === 'summary' ? 'Copied Text!' : 'Quick Text'}
          </button>

          <button
            onClick={handleDownloadJson}
            aria-label="Download complete brief as structured JSON data"
            className="flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-cyan-500/15 hover:bg-cyan-500/25 border border-cyan-500/40 text-xs font-semibold text-cyan-300 transition focus:outline-none focus:ring-2 focus:ring-cyan-400"
          >
            <Download className="w-4 h-4" aria-hidden="true" />
            Download JSON
          </button>
        </div>

        {/* Preview Container */}
        <div className="flex-1 overflow-y-auto rounded-xl bg-slate-950/80 border border-slate-800 p-4 font-mono-code text-xs text-slate-300 leading-relaxed space-y-2 select-all" tabIndex={0} role="region" aria-label="Markdown brief preview">
          <pre className="whitespace-pre-wrap">{generateMarkdown()}</pre>
        </div>

        <div className="mt-4 flex justify-end">
          <button
            onClick={onClose}
            aria-label="Close export dialog"
            className="px-5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 transition focus:outline-none focus:ring-2 focus:ring-slate-400"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
